name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/loadtest.js

      - run: ls & mkdir report & mv index.html report
      - name: step 4 - upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: status report load test
            path: report