name: Basic Workflow
on: [push]
permissions:
  contents: write

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/loadtest.js

      - run: ls & mkdir report & mv index.html report
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: status report load test
            path: report

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: report